# Generated by Django 3.1.3 on 2020-11-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writehat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagetemplate',
            old_name='background',
            new_name='backgroundImageID',
        ),
        migrations.RenameField(
            model_name='pagetemplate',
            old_name='logo',
            new_name='logoImageID',
        ),
    ]
