# Generated by Django 3.1.14 on 2022-08-02 07:29

from django.db import migrations
import writehat.models


class Migration(migrations.Migration):

    dependencies = [
        ('writehat', '0002_auto_20201120_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetemplate',
            name='header',
            field=writehat.models.MarkdownField(blank=True, max_length=30000, null=True),
        ),
    ]
